### PR TITLE
First pass at refactoring / polishing CMake build system

### PR DESCRIPTION
**Pull request by pramodk**
Before starting on NEURON, I thought I could quickly go through IV as well.

I tested on OSX as well as Linux. I hope I haven't broken anything for Windows.

cc: @ohm314  @iomaganaris

### CODE REVIEW

**Comment by wvangeit** [comment]
Is the plan also to merge the cmake into the master ?
And would cmake replace autoconf, or would both keep on existing at the same time.

When you want to replace autoconf with cmake I have a couple of reservations though:
- I'm not really sure it will make things easier for the user, in my experience configuring cmake commands is more complex from a user point of view (and for 'power' users, most people are used to the autoconf interface, while cmake is much less known)
- It adds another dependency. For example, on MacOS as far as I know (from my machine) cmake is not installed by default, and as opposed to autoconf, users would need cmake to install neuron from the tarball. (and there can also be issues if one has an outdated version of cmake installed)
- I agree that rewriting the build system might clean things up, but there is also a chance that the conversion would actually complicate things even more
- The current neuron autoconf implementation has been field-tested for years on presumably many many systems. If there is no period in which the two systems exist together, we might end up with a long time of debugging neuron install of users again.

**Comment by nrnhines** [comment]
It will eventually be merged with the master when/if it reaches the current coverage of autotools. The autotools build system will remain indefinitely.
CMake is definitely improving my own life with an order of magnitude faster build in many situations and
a promise of identical build process on windows. It solves (promises to solve) a bunch of issues with
neuron+coreneuron+sundials+readline+mpi+nmodlcore+packaging+...

**Comment by wvangeit** [comment]
Ok, as long as autotools will remain indefinitely, I don't have any problem at all with both system existing side-by-side.

**Comment by pramodk** [comment]
> Is the plan also to merge the cmake into the master ?
> And would cmake replace autoconf, or would both keep on existing at the same time.
> When you want to replace autoconf with cmake I have a couple of reservations though:
> Ok, as long as autotools will remain indefinitely, I don't have any problem at all with both system existing side-by-side.

Having built neuron on various platforms (x86, powerpc, arm, cray etc.) and seen build issues,  I also raised concerns for replacing autoconf. And hence, as Michael said, plan is to keep autoconf along with CMake.

Having said that:

> It adds another dependency. For example, on MacOS as far as I know (from my machine) cmake is not installed by default, and as opposed to autoconf, users would need cmake to install neuron from the tarball. (and there can also be issues if one has an outdated version of cmake installed)

* Now days, for any C/C++ project, getting CMake (v3.3) is quite simple...so extra dependency wouldn't be too much concern in my opinion.
* The goal of introducing CMake is to simplify the exiting build system, integrate other projects easily as well as improve user interface.

Now days there are many projects on GitHub that continuously build binaries for linux/macos/windows from master branch and I believe we can do better that what we have today.

Screenshot 2019-07-20 at 17 14 06

Before promising too much, main question would be whether it "works" in practice.  We will have experimental CMake option in place soon that we all can evaluate. And then we can decide best way forward.

**Pull request merged**
